all: main

main:
	g++ -o main main.cc

component:
	g++ -c component.cc -lSDL2

display:
	g++ -c display.cc -lSDL2

entity:
	g++ -c entity.cc

game: 
	g++ -c game.cc -lSDL2

input:
	g++ -c input.cc -lSDL2

prefabs:
	g++ -c prefabs.cc

renderer:
	g++ -c renderer.cc -lSDL2 -std=c++11

system:
	g++ -c system.cc

texture:
	g++ -c texture.cc -lSDL2 -lSDL2_image

time:
	g++ -c time.cc -lSDL2

transform:
	g++ -c transform.cc -lSDL2

wasdcontroller:
	g++ -c wasdcontroller.cc